### PR TITLE
Reference New Operator

### PR DESCRIPTION
**Pull request by nmanoogian**

### CODE REVIEW

**Review by rgmvisser — CHANGES_REQUESTED** [review]
Can we make it a little bit bigger and more prominent? :)

**Comment by nmanoogian** [comment]
> Can we make it a little bit bigger and more prominent? :)

How's that? The only way to really make it bigger is by putting it into a header, which always felt a little hacky to me. I'm not opposed though.

**Comment by rgmvisser** [comment]
> > Can we make it a little bit bigger and more prominent? :)
> 
> How's that? The only way to really make it bigger is by putting it into a header, which always felt a little hacky to me. I'm not opposed though.

Yeah probably an H1 or H2, maybe in combination of something like this? https://stackoverflow.com/questions/58737436/how-to-create-a-good-looking-notification-or-warning-box-in-github-flavoured-mar

**Comment by nmanoogian** [comment]
I like the table trick! Let me know what you think about that.

**Comment by rgmvisser** [comment]
Looks good, I would place it above the header though with some whitespace under it, otherwise it is easy to glance over

**Review by rgmvisser — APPROVED** [review]

**Pull request merged**
